### ISSUE TITLE
cupy divide does not support where argument

### ISSUE THREAD

**Issue by the-moliver** [slaue/genosolver#3]
I'm getting errors caused by this line (158-159) when trying to use cupy because the divide function in cupy does not support the where argument `step_ub = np.divide(self.ub - x, d, out=self.inf_array, where=d>0)`
Thanks!

**Comment by slaue** [comment]
This is a bit strange. I know that it was working before, i.e., cupy was supporting the 'where' option. (Surprisingly, it is an open issue in the cupy repository). We did run quite a bunch of experiments using cupy. Your suggestion will work. However, it will raise warnings when d = 0, which happens often. I will look into this issue more carefully. 

Minor comment: The line `step_ub = np.divide(self.ub - x, d, out=self.inf_array, where=d>0)` contained a bug and has been replaced, but it still contains there 'where' option though.
